### PR TITLE
SLING-8727: Fix NPE in SlingClient constructor

### PR DESCRIPTION
**Pull request by volteanu**
ping @dulvac @rombert

### CODE REVIEW

**Comment by raducotescu** [comment]
@volteanu, does https://issues.apache.org/jira/browse/SLING-8710 have something to do with this issue?

**Comment by volteanu** [comment]
nope, I created the branch on my fork with the wrong name. Should not impact anyhow the PR, right?

**Comment by raducotescu** [comment]
No, but I was asking so that I know how to build the PR. Unfortunately, due to some INFRA changes, we cannot automatically test PRs coming from people who don't have commit rights for Apache Sling.

**Comment by raducotescu** [comment]
Applied patch in 609cb61. Thanks, @volteanu!

**Pull request closed without merging**
